"""Regenerate adaptive_online_lqr_regret_simplified_sampling_band70.tex from a
Monte Carlo .npz produced by expc_run.py.

Templates the structure of the existing pgfplots file (colors, grid, legend,
band-then-line ordering) and replaces the coordinate data; axis size is set to
width=8cm, height=5cm (height:width = 5:8) per the paper's layout request.
Bands are percentile bands (default 70%: 15th-85th), lines are means --
matching the original figure's construction.
"""
import argparse

import numpy as np

SERIES = [
    ("fw", "FW", "steelblue31119180"),
    ("naive", "CE + Naive", "darkorange25512714"),
    ("sampling", "Sampling", "forestgreen4416044"),
]

HEADER = r"""% Generated by experiments/claude/expc_make_figure.py (Claude) from {src}
% Monte Carlo: {ns} seeds ({seed0}..{seed1}), mean line + {band:.0f}% percentile band.
\begin{{tikzpicture}}

\definecolor{{darkgrey176}}{{RGB}}{{176,176,176}}
\definecolor{{darkorange25512714}}{{RGB}}{{255,127,14}}
\definecolor{{forestgreen4416044}}{{RGB}}{{44,160,44}}
\definecolor{{lightgrey204}}{{RGB}}{{204,204,204}}
\definecolor{{steelblue31119180}}{{RGB}}{{31,119,180}}

\begin{{axis}}[
grid=both,
width=8cm,
height=5cm,
legend cell align={{left}},
legend columns=3,
legend style={{
  font=\normalsize,
  fill opacity=0.8,
  draw opacity=1,
  text opacity=1,
  at={{(0.5,1.12)}},
  anchor=south,
  draw=lightgrey204,
  /tikz/every even column/.append style={{column sep=0.5em}}
}},
tick align=outside,
tick pos=left,
x grid style={{darkgrey176}},
xlabel={{Time $t$}},
xmajorgrids,
xmin={xmin:.6g}, xmax={xmax:.6g},
xminorgrids,
xtick style={{color=black}},
y grid style={{darkgrey176}},
ylabel={{regret $R_t$}},
ymajorgrids,
ymin={ymin:.6g}, ymax={ymax:.6g},
yminorgrids,
ytick style={{color=black}}
]
"""


def downsample_idx(y_all, T, max_pts):
    """Index set 0..T-1: uniform stride plus endpoints."""
    stride = max(1, T // max_pts)
    idx = np.arange(0, T, stride)
    if idx[-1] != T - 1:
        idx = np.append(idx, T - 1)
    return idx


def fmt(v):
    return f"{v:.10g}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--npz", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--band", type=float, default=70.0)
    ap.add_argument("--max-points", type=int, default=250)
    args = ap.parse_args()

    d = np.load(args.npz, allow_pickle=False)
    seeds = d["seeds"]
    plo = 50.0 - args.band / 2.0
    phi = 50.0 + args.band / 2.0

    curves = {}
    T = None
    for key, _, _ in SERIES:
        arr = d[key]                      # (S, T)
        T = arr.shape[1]
        curves[key] = dict(
            mean=np.mean(arr, axis=0),
            lo=np.percentile(arr, plo, axis=0),
            hi=np.percentile(arr, phi, axis=0),
        )
    t = np.arange(1, T + 1)
    idx = downsample_idx(None, T, args.max_points)

    ylo = min(c["lo"][idx].min() for c in curves.values())
    yhi = max(c["hi"][idx].max() for c in curves.values())
    pad = 0.05 * (yhi - ylo)
    xpad = 0.05 * (T - 1)

    parts = [HEADER.format(src=args.npz.split("/")[-1], ns=len(seeds),
                           seed0=int(seeds.min()), seed1=int(seeds.max()),
                           band=args.band,
                           xmin=1 - xpad, xmax=T + xpad,
                           ymin=ylo - pad, ymax=yhi + pad)]

    # legend (paper order), decoupled from draw order so the FW line can be
    # drawn last (on top) where curves overlap
    for key, label, color in SERIES:
        parts.append(f"\\addlegendimage{{line width=1.6pt, {color}}}\n"
                     f"\\addlegendentry{{{label}}}\n")

    # percentile bands (same draw order as the original file)
    for key, _, color in SERIES:
        c = curves[key]
        pts_lo = [f"(axis cs:{t[i]},{fmt(c['lo'][i])})" for i in idx]
        pts_hi = [f"(axis cs:{t[i]},{fmt(c['hi'][i])})" for i in reversed(idx)]
        body = "\n--".join(pts_lo + pts_hi)
        parts.append(
            f"\\path [draw={color}, fill={color}, opacity=0.2]\n"
            + body + "\n--cycle;\n")

    # mean lines; proposed method (first in SERIES) drawn last, on top
    for key, label, color in SERIES[1:] + SERIES[:1]:
        c = curves[key]
        rows = "\n".join(f"{t[i]} {fmt(c['mean'][i])}" for i in idx)
        parts.append(
            f"\\addplot [line width=1.6pt, {color}, forget plot]\n"
            f"table {{%\n{rows}\n}};\n")

    parts.append("\\end{axis}\n\n\\end{tikzpicture}\n")
    with open(args.out, "w") as f:
        f.write("".join(parts))
    print(f"wrote {args.out}  (T={T}, {len(idx)} pts/curve, "
          f"band {plo:.0f}-{phi:.0f} pct, {len(seeds)} seeds)")
    for key, label, _ in SERIES:
        c = curves[key]
        print(f"  {label:11s} final mean={c['mean'][-1]:.4g} "
              f"band=[{c['lo'][-1]:.4g}, {c['hi'][-1]:.4g}]")


if __name__ == "__main__":
    main()
